# Generated by Django 2.0.4 on 2018-05-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20180501_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the Way'), (1, 'Pending'), (4, 'Delivered'), (2, 'Processing')]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.Order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shopapp.Product'),
        ),
    ]
