# Generated by Django 2.0.4 on 2018-05-02 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20180501_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('POD', 'PayPOD'), ('CARD', 'PayCard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(4, 'Delivered'), (2, 'Processing'), (3, 'On the Way'), (1, 'Pending')]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.Product'),
        ),
    ]
