# Generated by Django 2.0.4 on 2018-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_auto_20180502_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('POD', 'PayPOD'), ('CARD', 'PayCard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Processing'), (4, 'Delivered'), (3, 'On the Way'), (1, 'Pending')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(),
        ),
    ]
