# Generated by Django 2.0.4 on 2018-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20180502_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('PROCESSING', 'Processing'), ('PANDING', 'Pending'), ('DELIVERED', 'Delivered'), ('ON THE WAY', 'On the Way')]),
        ),
    ]
