# Generated by Django 2.0.4 on 2018-05-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20180502_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Processing'), (4, 'Delivered'), (1, 'Pending'), (3, 'On the Way')]),
        ),
    ]
