# Generated by Django 2.0.4 on 2018-05-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_auto_20180502_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('CARD', 'PayCard'), ('POD', 'PayPOD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the Way'), (1, 'Pending'), (4, 'Delivered'), (2, 'Processing')]),
        ),
    ]
