# Generated by Django 2.0.4 on 2018-05-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_auto_20180502_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('POD', 'PayPOD'), ('CARD', 'PayCard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(3, 'On the Way'), (1, 'Pending'), (2, 'Processing'), (4, 'Delivered')]),
        ),
    ]
