# Generated by Django 2.0.4 on 2018-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_auto_20180502_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(2, 'Processing'), (3, 'On the Way'), (1, 'Pending'), (4, 'Delivered')]),
        ),
    ]
